api_subdomain: api
admin_subdomain: admin

endpoint: http://api.zinger.pw

api_auth: lMkjDvjgc8r5dt2fY2gu13iX0kdjSXiBt6GfHihj
google_client_id: 1045854179918-k05hppi6h6ghdpkkg7mjjk6g82ae2bbo.apps.googleusercontent.com
