development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: zinger
  pool: 10
  username: root
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: zinger
  pool: 5
  username: root
  password: password
